import PublicHeader from "@/components/Public-Header";
import "./globals.css";
import { StoreProvider } from "@/store/StoreProvider";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Mi lista del Super en Barcelona",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <StoreProvider>
                    <PublicHeader />
                    {children}
                </StoreProvider>
            </body>
        </html>
    );
}
